apiVersion: v1
kind: Service
metadata:
  name: mednet-q-service
  namespace: production
  labels:
    app: mednet-q
spec:
  type: NodePort
  selector:
    app: mednet-q
  ports:
    # Web UI port
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30880  # You can change this to any available port in 30000-32767 range
    
    # SMTP port
    - name: smtp
      port: 2525
      targetPort: 2525
      protocol: TCP
      nodePort: 30525  # You can change this to any available port in 30000-32767 range