apiVersion: v2
name: smtp-relay
description: A Helm chart for SMTP Relay Service - Medical Grade Email Infrastructure
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - smtp
  - email
  - relay
  - medical
  - healthcare

home: https://github.com/The-Mednet/smtp-relay
sources:
  - https://github.com/The-Mednet/smtp-relay

maintainers:
  - name: Mednet Infrastructure Team
    email: infrastructure@mednet.com
    url: https://mednet.com

dependencies:
  - name: mysql
    version: 9.4.6
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: 17.15.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 15.18.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled

annotations:
  category: Infrastructure
  images: |
    - name: smtp-relay
      image: smtp-relay:1.0.0
    - name: mysql
      image: mysql:8.0
    - name: redis
      image: redis:7.0-alpine