---
# Main SMTP service for internal cluster communication
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay-service
  namespace: mednet-email
  labels:
    app: smtp-relay
    component: email-processor
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: smtp-relay
  ports:
  - name: smtp
    port: 2525
    targetPort: 2525
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Local  # For better performance and source IP preservation

---
# Web UI service for management interface
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay-webui
  namespace: mednet-email
  labels:
    app: smtp-relay
    component: webui
spec:
  type: ClusterIP
  selector:
    app: smtp-relay
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP

---
# Metrics service for Prometheus scraping
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay-metrics
  namespace: mednet-email
  labels:
    app: smtp-relay
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: smtp-relay
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP

---
# Headless service for StatefulSet (if needed for distributed coordination)
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay-headless
  namespace: mednet-email
  labels:
    app: smtp-relay
    component: coordination
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: smtp-relay
  ports:
  - name: smtp
    port: 2525
    targetPort: 2525
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP